#ifndef ELF_TOOLCHAIN_ERROR_CODES_H
#define ELF_TOOLCHAIN_ERROR_CODES_H

#define OPEN_ERROR (-1)
#define STAT_ERROR (-1)
#define READ_ERROR (-1)
#define WRITE_ERROR (-1)
#define CLOSE_ERROR (-1)
#define MUNMAP_ERROR (-1)
#define MPROTECT_ERROR (-1)

#endif //ELF_TOOLCHAIN_ERROR_CODES_H
